[settings]
experimental = true
# Uncomment to automatically install tools when entering a directory
# auto_install = true

[tools]
node = "lts"
python = "latest"
# go = "latest"
# rust = "latest"

[env]
# Global env vars go here
